### ISSUE TITLE
Path to config.json in docker

### ISSUE THREAD

**Issue by Sav3k** [notclickable-jordan/starbase-80#19]
Hi there, i'm trying to install starbase on my unraid system using the ibracorp-template and running into some issues. As per the documentation Starbase expects a direct path allocation to the config.json, which is afaik not possible, because you can't directly point to a file, only a path. Setting the Config-Path to the folder containing the config.json unfortunately doesn't work either. Am i missing something? Some help would be greatly appreciated, since starbase looks quite awesome.

**Comment by notclickable-jordan** [comment]
Sure, I can try to help. It sounds like Unraid doesn't let you do bind mounts to individual files? If that's the case, you can use volume mounts to the /config directory.

Can you put your Unraid config file for Starbase 80 here?

**Comment by Sav3k** [comment]
When i try to bind the config.json directly to the file, just as mentioned in the doc unraid pops an error saing: "not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)?" which leads me to believe that this is indeed not possible. What do you mean by volume mounts?
Config file is still the sample one, since i didn't get the docker to start running anyway. Thanks for the fast reply!

**Comment by notclickable-jordan** [comment]
In Docker, you can mount a file on your system to a file in the Docker container. That's a bind mount. It can also be folder to folder.

You can also use a volume, which is a special Docker "hard drive" on your system that looks like a folder to the Docker container. I recently changed how Starbase 80 works so it can support volumes for the config.json.

I've never used Unraid, so I need to see what you're seeing when you try to get Starbase 80 running. Show me your config files and error messages and I can try to help.

**Comment by Sav3k** [comment]
Sure, this is the full error-message: 

docker run
  -d
  --name='starbase'
  --net='bridge'
  -e TZ="Europe/Berlin"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Main"
  -e HOST_CONTAINERNAME="starbase"
  -e 'TITLE'=''
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:4173]'
  -l net.unraid.docker.icon='https://i.imgur.com/dMTz5iU.png'
  -p '4173:4173/tcp'
  -v '/mnt/user/appdata/starbase/config.json':'/app/src/config.json':'rw'
  -v '/mnt/user/appdata/starbase/icons':'/app/public/icons':'rw' 'jordanroher/starbase-80'
b297b9035da5e8ddc6b75a44b5a9752bf86cac2fdb24790f29217c555535d7db
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/mnt/user/appdata/starbase/config.json" to rootfs at "/app/src/config.json": mount /mnt/user/appdata/starbase/config.json:/app/src/config.json (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

these are the avaiable settings in the unraid-docker configurator: 

<img width="609" alt="Screenshot 2023-12-16 at 20 46 33" src="https://github.com/notclickable-jordan/starbase-80/assets/82757271/9b9834a4-649a-4bfd-b84d-f5ce180f4913">

**Comment by notclickable-jordan** [comment]
Based on this part:
> Check if the specified host path exists and is the expected type.

It makes me think that the file on your system (host path) doesn't exist. Can you verify that `/mnt/user/appdata/starbase/config.json` is there?

**Comment by Sav3k** [comment]
Ok so the thing is, unraid always created the folder "config.json" when adding this allocation - i had to manually delete it, now at least this problem seems solved - thank you! Starbase still doesn't start though: 

> starbase-80@1.3.0 start
> node start.js

Building React site
Error executing command: Error: Command failed: npm run build

An error occurred: Error: Command failed: npm run build

    at genericNodeError (node:internal/errors:956:15)
    at wrappedFn (node:internal/errors:510:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 2,
  killed: false,
  signal: null,
  cmd: 'npm run build'
}

**Comment by notclickable-jordan** [comment]
Hmm. I don't have enough information from that to know what's going on. It should be fine, considering it's a Docker image. Are there any other logs you can post?

Alternately, try an older tag for the image, i.e. `jordanroher/starbase80:1.2.0`

**Comment by Sav3k** [comment]
Well i got it somewhat running now - seems to be that the template that exits is rather rubbish. Thanks for all the support!
