### ISSUE TITLE
How to enable dark theme

### ISSUE THREAD

**Issue by NickHatBoecker** [notclickable-jordan/starbase-80#23]
Hello, I want to enable dark theme but can't find any way to do this.
I'm not using dark mode on my mac, but I want to force dark mode nonetheless.
I run starbase in docker.

Things I tried:
- set THEME env variable
- changed `export const THEME = "light";` to `export const THEME = "dark";` in `src/variables.ts`
- I couldn't even find the line where `THEME` is used

Can you please help me?

**Comment by notclickable-jordan** [comment]
You're right, I forgot to finish the manual dark mode selector. It's fixed in 1.5.0. #24
