### ISSUE TITLE
ST:LD S05E05 SB-80 artwork easter egg

### ISSUE THREAD

**Issue by abrugsch** [notclickable-jordan/starbase-80#36]
Since the recent (Nov 14th 2024) episode dedicated to SB-80, there should probably be some reference to the canon visual given to the TOS era station ;)
Either in the logo or as a hidden easter egg somewhere...

**Comment by notclickable-jordan** [comment]
Awesome, I've got to watch that episode! I'll figure out something.

**Comment by abrugsch** [comment]
It's a great episode! You won't be disappointed.
