### ISSUE TITLE
Add Docker & Ping Status support

### ISSUE THREAD

**Issue by viriatusX** [notclickable-jordan/starbase-80#5]
Hi!
It would be wonderful if you would add support for Docker and Ping Status 🙏.
The design and functionality are perfect; congratulations on your work 👏.

Thanks!!

**Comment by notclickable-jordan** [comment]
Acknowledged. It will be a while before I get to this.

**Comment by viriatusX** [comment]
> Acknowledged. It will be a while before I get to this.

Any news? Thanks for your work!

**Comment by notclickable-jordan** [comment]
I only get an hour a day of free time. Right now I'm playing Tears of the Kingdom. Sorry, but it's going to be a while before I get back to this.

**Comment by notclickable-jordan** [comment]
Sorry, I'm not going to be going in this direction. I want the site to be as minimal as possible, so I rewrote it in plan TypeScript. React has been removed and the whole thing is static. You're welcome to [go back to an old commit](https://github.com/notclickable-jordan/starbase-80/commit/902e0fea3cb47590f72f69b623a16ec6d533799c) and fork it.
