### ISSUE TITLE
NGINX Subfolder

### ISSUE THREAD

**Issue by s33d1ing** [notclickable-jordan/starbase-80#7]
I'm trying to configure Starbase to run in a subfolder using LinuxServer's [SWAG ](https://github.com/linuxserver/docker-swag) container. I've was able to get all links and icons to load using the following NGINX block, but the favicon is not loading. Does anyone know what needs to be rewritten or filtered to get favicon to load?

``` NGINX
location ^~ /starbase {
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;

    set $upstream_app starbase;
    set $upstream_port 4173;
    set $upstream_proto http;

    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    proxy_set_header Accept-Encoding "";

    proxy_redirect ~^/(.*)$ /starbase/$1;
    rewrite ^/starbase/?(.*)$ /$1 break;

    sub_filter_once off;
    sub_filter_types *;

    sub_filter '/assets' '/starbase/assets';
    sub_filter '/icons'  '/starbase/icons';

    sub_filter '/favicon.ico' '/starbase/favicon.ico';
    sub_filter '/logo.png'    '/starbase/logo.png';
}
```

**Comment by notclickable-jordan** [comment]
Your redirects look fine. Maybe the problem is that the app doesn't specifically ask for a favicon? I just pushed a new version that includes `<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />` in the `<head>` tag. Try that.

**Comment by s33d1ing** [comment]
That did the trick. Thank a bunch!
