### ISSUE TITLE
Icon image aspect ratio

### ISSUE THREAD

**Issue by viharm** [notclickable-jordan/starbase-80#8]
Firstly, thanks for developing this tool. I love it's simplicity - for when one wants simply a start page with no frills.

The integration with MDI & Dashboard icons is just the right amount of complexity to allow quick and easy setup of the "dashboard" without having to save icons - thanks :-)

I've been creating categories and services, and noticed that many icons don't respect the aspect ratio of the image used, as the placeholder for all icons appears to be square. I'd suggest testing with the "costco" or "startpage" dashboard icons.

Is there a way to tweak this behaviour. I recognize that this will cause the icons to be much smaller, but this might be a preference for some like me.

I'm wondering if it is worth looking into.

**Comment by notclickable-jordan** [comment]
Thanks for reporting this! I added an option to icons to allow them to constrained aspect ratios by width or height. Let me know if that works for you.

**Comment by viharm** [comment]
Hi @notclickable-jordan , thanks for the prompt action on this. I’ve done an initial test with the “costco” icon, which works well. Thanks.
